
[versions]
agp = "8.10.1"
kotlin = "2.0.0"

compose-bom = "2024.09.02"

# AndroidX
androidx-core = "1.13.1"
lifecycle = "2.8.5"
navigation = "2.8.0"
activity = "1.9.2"
datastore = "1.1.3"
credentials = "1.3.0"
room = "2.6.1"
work = "2.9.1"
androidx-test = "1.6.1"

# DI
androidx-hilt = "1.2.0"
dagger = "2.52"

# Network / Serialization
retrofit = "2.9.0"
moshi = "1.13.0"
serialization = "1.8.0"

# Firebase
firebase-bom = "33.3.0"
geofire = "3.2.0"

# Test
jupiter = "5.11.4"
junit5-android = "1.4.0"
androidx-test-ext-junit = "1.1.5"
espresso = "3.6.1"

# Google / Play services
googleid = "1.1.1"
play-services-location = "21.3.0"
play-services-ads = "24.4.0"

# Other libs
mockk = "1.13.13"
mockito-junit-jupiter = "3.9.0"
lottie-compose = "6.5.2"
sulky-ulid = "8.2.0"
kakao-maps = "2.11.9"
naver-maps = "3.22.1"
komoran = "3.3.9"
timber = "5.0.1"
compose-shimmer = "1.3.3"
landscapist-glide = "2.4.0"
ui-automator = "2.3.0"
coroutines-play-services = "1.9.0"
coroutines-test = "1.10.2"
turbine = "1.2.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library     = { id = "com.android.library", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
# Plugin
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin  = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }


# Kotlin BOM / Coroutines / Serialization
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines-play-services" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

# AndroidX core
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }

# Lifecycle
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# Activity / Navigation
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

# DataStore / Credentials
androidx-datastore-preferences-core-jvm = { module = "androidx.datastore:datastore-preferences-core-jvm", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }

# Misc AndroidX
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version = "1.3.7" }
androidx-browser = { module = "androidx.browser:browser", version = "1.8.0" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version = "1.1.0" }

# Hilt (AndroidX integration)
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
androidx-hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "androidx-hilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidx-hilt" }

# Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

# WorkManager
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

# AndroidX Test
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "ui-automator" }

androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

# Compose (BOM)
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

# Dagger / Hilt
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }

# Retrofit / Moshi
squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
squareup-moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }

# Firebase (BOM)
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-database = { module = "com.google.firebase:firebase-database" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }

# Google
google-identity-googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
google-play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
google-play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "play-services-ads" }

# Other libs
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito-junit-jupiter" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie-compose" }
sulky-ulid = { module = "de.huxhorn.sulky:de.huxhorn.sulky.ulid", version.ref = "sulky-ulid" }

kakao-maps = { module = "com.kakao.maps.open:android", version.ref = "kakao-maps" }
naver-maps = { module = "com.naver.maps:map-sdk", version.ref = "naver-maps" }
komoran = { module = "com.github.shin285:KOMORAN", version.ref = "komoran" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
compose-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "compose-shimmer" }
landscapist-glide = { module = "com.github.skydoves:landscapist-glide", version.ref = "landscapist-glide" }

firebase-geofire-android = { module = "com.firebase:geofire-android", version.ref = "geofire" }
firebase-geofire-android-common = { module = "com.firebase:geofire-android-common", version.ref = "geofire" }

# Unit test
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "jupiter" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }

junit5-android-test-core = { module = "de.mannodermaus.junit5:android-test-core", version.ref = "junit5-android" }
junit5-android-test-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "junit5-android" }

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test" }
cash-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }


[bundles]
androidx-lifecycle = ["androidx-lifecycle-runtime-ktx", "androidx-lifecycle-viewmodel-compose"]
room = ["androidx-room-runtime", "androidx-room-ktx"]
retrofit-moshi = ["squareup-retrofit", "squareup-retrofit-converter-moshi", "squareup-moshi-kotlin"]